---

- name: deploy static content to webserver
  hosts: tag_Type_webserver
  become: true
  serial: 1
  pre_tasks:
  - name: Gathering ec2 facts
    action: ec2_facts
  - name: Instance De-register
    local_action:
      module: ec2_elb
      region: "{{ aws_region }}"
      instance_id: "{{ ansible_ec2_instance_id }}"
      state: absent
  roles:
    - { role: ngnix, dispatch: ['deploy-static']}
  post_tasks:
  - name: Instance Register
    local_action:
      module: ec2_elb
      region: "{{ aws_region }}"
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "{{ item }}"
      state: present
    with_items: "{{ ec2_elbs }}"
