---

- name: provision EC2 instance
  ec2:
    key_name: "{{ key_name }}"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ ami_id }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    group: "{{ aws_vm_groups }}"
    region: "{{ aws_region }}"
    count_tag:
      Name: "{{ name }}"
    exact_count: "{{ count }}"
    zone: "{{ zone }}"
    instance_tags:
      Name: "{{ name }}"
      Type: "{{ type }}"
    assign_public_ip: "{{ public_faced }}"
    wait: yes
  register: aws_vms

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ aws_vms.instances }}"
