---

- name:  Ensure tomcat group
  group:
    name: "{{ tomcat_group }}"

- name:  Ensure tomcat user
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    shell: /bin/bash

- name:  Create logs path
  file:
    path: "{{ tomcat_logs_path }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  when: tomcat_logs_path is defined

- name:  Create install path
  file:
    path: "{{ tomcat_install_path }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name:  Check Tomcat version
  command: "java -cp {{ tomcat_install_path }}/lib/catalina.jar org.apache.catalina.util.ServerInfo | grep 'Server version' | sed 's/Server version: //g'"
  register: tomcat_check
  changed_when: false
  ignore_errors: true

- name:  Download & Extract Tomcat
  unarchive:
    extra_opts: ['--strip-components=1']
    src: "{{ tomcat_url }}"
    remote_src: yes
    dest: "{{ tomcat_install_path }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0750
  when: 'tomcat_check|failed or tomcat_check.stdout == "Apache Tomcat/tomcat_version"'
  notify: start tomcat

- name: copy jks keystore
  copy:
    src: "../../config/{{ keystoreFile }}"
    dest: "{{ tomcat_conf_path }}/{{ keystoreFile }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0750

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

- name: Configure Tomcat server
  template:
    src: server.xml.j2
    dest: "{{ tomcat_conf_path }}/server.xml"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0750
  notify: restart tomcat

- name: Configure Tomcat users
  template:
    src: tomcat-users.xml.j2
    dest: "{{ tomcat_conf_path }}/tomcat-users.xml"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0640
  notify: restart tomcat
